---
title: "Case-Cohort Estimator"
author: "Suzanne Dufault"
date: "2021-08-04"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE,
                      fig.path = "graphs/")
library(here)
library(tidyverse)
library(geodist)
library(knitr)
library(kableExtra)
library(lme4)

load("data/2020-12-08_work-ts-spat.RData")
source("lib/case-cohort-estimator.R")
```

## Case-Cohort Analyses {.tabset}

```{r df-all-dengue}
work_all_dengue <- work_ts_spat %>% 
  # Removing the unknown serotypes
  filter(serotype != "unk_serotype") %>% 
  dplyr::select(-serotype) %>% 
  distinct()
```

```{r all-dengue-rr-t}
# time
t <- c(7,14,30) # MODIFY THIS
# distances 
r.upper <- c(100,200,500) # MODIFY THIS
r.lower <- c(0,0,0) # MODIFY THIS - must be the same length as r.upper

# This runs the case-cohort function with the pre-specified times and distances
output_all_t <- case_cohort_function(dataset = work_all_dengue,
                               d1 = r.lower,
                               d2 = r.upper,
                               time = t)
```

### Contingency Table Results
```{r lineplot-case-cohort-contingency-or}
output_all_t$contingency.table %>% 
  ungroup() %>% 
  filter(dengue == 1) %>% 
  mutate(days = as.factor(time)) %>% 
  ggplot(aes(x = distance2, y = rr, col = days, fill = days)) +
  facet_wrap(~days, ncol = 1) +
  geom_line() + 
  geom_ribbon(aes(ymin = CI.l, ymax = CI.u),
              alpha = 0.3,
              col = "white") +
  geom_hline(yintercept = 1, lty = 2) + 
  ggpubr::theme_pubr() +
  xlab("Distance from a VCD (m)") +
  ylab("Case-Cohort Odds Ratio") + 
  theme(legend.position = "none")

output_all_t$contingency.table %>% 
  ungroup() %>% 
  filter(dengue == 1) %>% 
  mutate(days = as.factor(time)) %>% 
  dplyr::select(distance = distance2, days, or = rr, CI.l, CI.u) %>% 
  kable(digits = 2) %>% 
  kable_styling() %>% 
  collapse_rows(columns = 2)
```

### Mixed Effects Results

```{r lineplot-case-cohort-mixed-effects-or}
mixed_effects_estimates <- map(output_all_t$mixed.effects.results, ~summary(.)$coefficients) %>% 
  map_dfr(~.["exposure",1:2], # extract the estimated log or (column 1) and estimated Standard Error (column 2) for the exposure variable
          .id = "distance.time") %>% 
  mutate(or = exp(Estimate),
         CI.l = exp(Estimate - 1.96*`Std. Error`),
         CI.u = exp(Estimate + 1.96*`Std. Error`),
         distance = as.numeric(str_match(distance.time, "d\\s*(.*?)\\.t")[,2]),
         days = str_split_fixed(distance.time, pattern = ".t", n = 2)[,2]) %>% 
  mutate(days = factor(days, levels = c("7", "14", "30"))) 

mixed_effects_estimates %>% 
  ggplot(aes(x = distance, y = or, col = days, fill = days, group = days)) + 
  facet_wrap(~days, ncol = 1) +
  geom_line() +
  geom_ribbon(aes(ymin = CI.l, ymax = CI.u),
              alpha = 0.3,
              col = "white") +
  geom_hline(yintercept = 1, lty = 2) + 
  ggpubr::theme_pubr() +
  xlab("Distance from a VCD (m)") +
  ylab("Case-Cohort Odds Ratio") + 
  theme(legend.position = "none")

mixed_effects_estimates %>% 
  dplyr::select(distance, days, or, CI.l, CI.u) %>% 
  kable(digits = 2) %>% 
  kable_styling() %>% 
  collapse_rows(columns = 2)
```

### Side-by-Side Estimate Comparison

```{r side-by-side-comparison}
cont.results <- output_all_t$contingency.table %>% 
  ungroup() %>% 
  filter(dengue == 1) %>% 
  dplyr::select(distance = distance2,
                days = time,
                or = rr, 
                CI.l, CI.u) %>% 
  mutate(days = as.factor(days),
         type = "contingency table") 

me.results <- mixed_effects_estimates %>% 
  dplyr::select(-distance.time, -Estimate, - `Std. Error`) %>% 
  mutate(type = "mixed effects")
  
cont.results %>% 
  bind_rows(me.results) %>% 
  ggplot(aes(x = distance, y = or, col = type, fill = type)) +
  facet_wrap(~days, ncol = 1) +
  geom_line() + 
  geom_ribbon(aes(ymin = CI.l, ymax = CI.u),
              alpha = 0.3,
              col = "white") +
  geom_hline(yintercept = 1, lty = 2) + 
  ggpubr::theme_pubr() +
  xlab("Distance from a VCD (m)") +
  ylab("Case-Cohort Odds Ratio") +
  theme(legend.position = "bottom")
```

