---
title: "Case-Cohort Code Walk Through"
author: "Suzanne Dufault"
date: "2021-08-04"
output: 
  html_document:
    css: style.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Objective {.tabset}

[Background Overleaf Document](https://www.overleaf.com/read/mhyrrcbmmccb)

This document walks through the code I have written to set up the case-cohort estimator. There are 2 files you will need:

+ `case-cohort-results.Rmd` - this is a current template that builds a report of the analyses to date. 
+ `case-cohort-estimator.R` - this contains the actual estimation code. 

First, let's look at the estimator script. Then, we'll set up the report.

## The estimator: `case-cohort-estimator.R`

:::: {.blackbox data-latex=""}
For your work, you will need to modify lines 61-74 to get the (mixed effects/ GEE) logistic regression results.
::::

I have written the case-cohort function to take in three arguments: 

+ `dataset` - Data with arguments: 
    + `participant_id` 
    + `illness_onset` (date of illness onset)
    + `dengue` (0 = test-negative, 1 = test-positive) 
    + `longitude` 
    + `latitude`
+ `d1` - this argument sets the *lower bound* on the distance interval of interest. Typically, this is set to 0.
+ `d2` - this argument sets the *upper bound* on the distance interval of interest. Typically, this will range in 100m increments from 100 to 1,000.
+ `time` - this argument sets the time interval of interest. Typically, this will be 30 days.


### Setting up the data

I have attempted to include comments throughout the script itself that should identify what each part of the code is doing. The first few are lines are somewhat self-explanatory. First, we arrange the individuals in temporal order according to reported date of illness onset. Then we identify which of these individuals are virologically-confirmed (aka test-positive) dengue cases.

```
temp <- dataset %>% 
    # CRITICAL - put the individuals in time order according to date of illness onset
    arrange(illness_onset)
  
# Identify the test-positive dengue cases
vcd_ids <- temp$participant_id[temp$dengue == 1]
```

### Calculating the time and distance between each date of illness onset

The next lines of code produce two matrices with dimensions 6,239 $\times$ 6,239. The first matrix (`dist_temp`) contains all pairwise distances between the enrolled individuals. The second matrix (`time_temp`) contains all pairwise differences in time of illness onset between the enrolled individuals.

```
# Setting up distance and time matrices
dist_temp <- geodist(x = cbind(lon = temp$longitude, lat = temp$latitude), y = cbind(lon = temp$longitude, lat = temp$latitude))
time_temp <- expand.grid(temp$illness_onset, temp$illness_onset)
time_temp <- matrix(as.Date(time_temp$Var1) - as.Date(time_temp$Var2), nrow = nrow(temp))
```

Then, the diagonals are replaced with `NA` so that individuals may not be compared against themselves, and the rows and columns are renamed with the participant ids so that we can identify which pairs are being compared.

```
diag(dist_temp) <- diag(time_temp) <- NA
rownames(dist_temp) <- rownames(time_temp) <- temp$participant_id
colnames(dist_temp) <- colnames(time_temp) <- temp$participant_id
```

### Assigning exposure

The next, and **most important part of the code**, assigns exposure status using a series of `for` loops that allow you to iterate over different time and/or distance intervals without having to run the function itself over and over. Let's just look at some of the key pieces of code here.

The following two lines use the pairwise time and distance matrices to identify which individuals' illness onset fall within a given `time` of each other and which individuals' pairwise distance falls within a give range (`d1`,`d2`) in meters.

```
time_temp.bin <- 1*(time_temp < time[i] & time_temp >= 0)
dist_temp.bin <- 1*(dist_temp >= d1[j] & dist_temp < d2[j])
```

Next, we want to know which individuals were close in time AND distance, so we can multiply the indicator matrices together.

```
prod_mat <- time_temp.bin*dist_temp.bin # only indicates if anyone is within time and space of each other, to determine exposure, need to focus on vcds
```

Now we have a clear set of individuals who are close in time AND space. Next, to identify exposure, we want to know which individuals were VCDs, since *proximity to a VCD is our exposure of interest*. Let's extract just the columns corresponding to individuals who were VCDs from the matrix with proximate individuals.

```
exposure_set <- prod_mat[,which(colnames(prod_mat) %in% vcd_ids)]
```

Then, we look across each participant row to see if these VCDs were proximate and proceeded illness onset. If yes, then the participant is exposed. If no, then the participant is unexposed. **THIS IS HOW THE EXPOSURE OF INTEREST IS CODED.**

```
t1 <- unlist(apply(exposure_set, 1, function(x){max(x,na.rm = TRUE)}))
```

:::: {.blackbox data-latex=""}
::: {.center data-latex=""}
**Illustrative Example**
:::

Since the previous lines of code aren't inherently intuitive, here's a simple example. Let's say our `exposure_set` looks as follows:


|  | id01 | 
|--:|:---:|
| id01 | NA |
| id02 | 1  |
| id03 | 0  |
| id04 | 0  |

From the columns, we see that there is 1 virologically confirmed dengue case (id01). From the rows, we see that there were 4 individuals that had illness onset and residential locations that were considered proximate to at least one other person in the set in space and time.

`id01` is not compared against itself, therefore the first entry is `NA`.    
`id02` must have been close to `id01` in space AND time, therefore, the 2nd entry is 1.   
`id03` and `id04` were not close to `id01` in space and/or time, therefore, their entries are 0. (They may have been close to `id02` or each other, which is why they are included in the table.) 

In this simple example the column `id01` from the `exposure_set` will be equivalent to `t1`. If there were more columns, the `t1` line of code would produce a column that contains a 1 if there are ANY proximate VCDs near a participant and 0 otherwise.
::::

### Contingency table set up and estimation

The remaining lines simple produce the start of the 2 $\times$ 2 table which is useful for doing contingency style odds ratio estimation. If you run these lines and then look at the output, it will look something like the following (though numbers will change).

In this example, there were 620 test-negatives that had illness onset within 30 days and a residence within 200m of a virologically confirmed dengue case. There were 171 virologically confirmed dengue cases that had illness onset within 30 days and a residence within 200m of a virologically confirmed dengue case.

```
> temp2 <- data.frame(participant_id = names(t1), t1) %>% 
        full_join(dplyr::select(temp, c(participant_id, dengue))) %>% 
        group_by(dengue) %>% 
        summarise(exposed = sum(t1)) %>% 
        mutate(time = time[i],
               distance1 = d1[j],
               distance2 = d2[j])
               
> temp2              
# A tibble: 2 x 5
  dengue exposed  time distance1 distance2
   <dbl>   <dbl> <dbl>     <dbl>     <dbl>
1      0     620    30         0       200
2      1     171    30         0       200
```

To identify how many individuals remained unexposed, we can subtract these values from the total numbers of dengue-positive and negative participants. In this example (below), there are 5301 test-negatives that are unexposed and 214 virologically confirmed dengue cases that are unexposed. 

```
> ## Producing simple contingency tables and contingency table-based estimates
> contingency.table <- temp %>% 
    group_by(dengue) %>% 
    summarise(total = n_distinct(participant_id)) %>% 
    full_join(output) %>% 
    mutate(unexposed = total - exposed) %>% 
    group_by(time, distance1, distance2) %>% 
    mutate(numerator = exposed[dengue == 1]*unexposed[dengue == 0], 
           denominator = exposed[dengue == 0]*unexposed[dengue == 1]) %>% 
    mutate(rr = numerator/denominator) %>% 
    mutate(var.log.rr = 1/exposed[dengue == 1] + 1/exposed[dengue == 0] + 1/unexposed[dengue == 1] + 1/unexposed[dengue == 0]) %>% 
    mutate(CI.l = exp(log(rr) - 1.96*sqrt(var.log.rr)),
           CI.u = exp(log(rr) + 1.96*sqrt(var.log.rr)))
           
> contingency.table
# A tibble: 2 x 13
# Groups:   time, distance1, distance2 [1]
  dengue total exposed  time distance1 distance2 unexposed numerator denominator    rr var.log.rr  CI.l  CI.u
   <dbl> <int>   <dbl> <dbl>     <dbl>     <dbl>     <dbl>     <dbl>       <dbl> <dbl>      <dbl> <dbl> <dbl>
1      0  5921     620    30         0       200      5301    906471      132680  6.83     0.0123  5.50  8.49
2      1   385     171    30         0       200       214    906471      132680  6.83     0.0123  5.50  8.49
> 

```

To set up the 2 $\times$ 2 table, we then have:

| | VCD ($D$)| Test-negative ($\bar{D}$) |   
|--|:--:|:--:|
| $E$ | 171 | 620 |
| $\bar{E}$ | 214 | 5301 |

The rest of the columns of the output simply include the results from the following estimation (Note: OR $\approx$ RR for case-cohort): 

$OR = ad/bc = \frac{171 \times 5301}{214 \times 620} = 6.832009$
$Var(\log OR) = \frac{1}{a} + \frac{1}{b} + \frac{1}{c} + \frac{1}{d} = \frac{1}{171} + \frac{1}{620} + \frac{1}{214} + \frac{1}{5301} = 0.0123224$

### Model-based estimates

Beginning on line 61, I have an example mixed effects model with cluster ($i = 1,...,24$) as a random intercept and exposure as a fixed effect, corresponding to the following equation: 

\[\text{logit}(\mathbb{E}[Y|\text{exposure}]) = \beta_{0} + \beta_{0i} + \beta_1 \mathbb{I}(\text{exposure} = 1) \]

Now, $\beta_1$ is the log odds of dengue ($Y$) for an exposed individual compared to an unexposed individual, holding the study cluster fixed. 

```
## More complicated individual-level modeling (GEE, mixed effects, etc.)
mixed.effects.results <- NULL
  for (i in 1:ncol(exposures)){ # loop through the various exposures, as determined by times and distances
    mixed.effects.model <-  temp %>% 
      full_join(data.frame(participant_id = rownames(exposures), exposure = exposures[,i])) %>% 
      arrange(cluster) %>% 
      glmer(dengue ~ (1 | cluster) + exposure,
            family = binomial,
            data = .)
    
    mixed.effects.results <- append(mixed.effects.results,
                                  mixed.effects.model)
    names(mixed.effects.results)[i] <- colnames(exposures)[i]
  }
```

Finally, the last lines put the contingency table results and the mixed effects model results into a list so that you can save and recall them easily for any reports/needs you may have.

## Setting up the report: `case-cohort-results.Rmd`

The top of the report simply sets up the basics of the document. Feel free to change the title, author and date.

```
---
title: "Case-Cohort Estimator"
author: "Suzanne Dufault"
date: "3/24/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---
```

If you want to look at more options (for prettier reports), see [R Markdown: The Definitive Guide](https://bookdown.org/yihui/rmarkdown/html-document.html).

Next, in the `setup` code chunk, I call in the packages and data that I will need.

```
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)
library(here)
library(tidyverse)
library(geodist)
library(knitr)
library(kableExtra)
library(lme4)

load(here("data", "2020-12-08_work-ts-spat.RData"))
source(here("lib", "case-cohort-estimator.R"))
```

As long as you leave all of the files in the folders provided, you will not need to change any of this code to call in the data or the estimator script. 

### Setting up the data

First, we're going to remove any dengue cases with unknown serotypes. Even though this currently isn't particularly relevant, if more advanced decisions are made on a serotype-by-serotype basis, this will be a necessary step.

```
work_all_dengue <- work_ts_spat %>% 
  # Removing the unknown serotypes
  filter(serotype != "unk_serotype") %>% 
  dplyr::select(-serotype) %>% 
  distinct()
```

**The most relevant part of this script is identifying the time (t) and distance windows (r.upper, r.lower). YOU WILL NEED TO MODIFY THESE.** 


Currently, this means you need to modify lines 39, 41, and 42.
```
# time
t <- c(7,14,30) # MODIFY THIS
# distances 
r.upper <- c(100,200,500) # MODIFY THIS
r.lower <- c(0,0,0) # MODIFY THIS - must be the same length as r.upper
```

Then, running the contingency table estimates and mixed effects models is as simple as running line 45.

```
# This runs the case-cohort function with the pre-specified times and distances
output_all_t <- case_cohort_function(dataset = work_all_dengue,
                               d1 = r.lower,
                               d2 = r.upper,
                               time = t)
```

That's literally it. The rest of the document demonstrates how to extract/plot the results. 

Happy to discuss!



